name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Echo Test
        run: echo "Running basic tests!"

      - name: Build Docker image
        run: docker compose up -d --build
        
      - name: Wait for API run
        run: sleep 5

      #доступность адреса + состояние контейнеров
      - name: Ping API
        run: |
          curl -X GET --fail http://127.0.0.1:3000 || exit 1
          docker ps -a

      - name: check DB
        run: docker logs web-mariadb-16
      
      - name: init DB
        run: curl -X GET http://127.0.0.1:3000/initDB
      

      - name: Send data and get student
        run: | 
          curl --location 'http://127.0.0.1:3000/result' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'lastName=df' --data-urlencode 'firstName=df' --data-urlencode 'patronymic=df' --data-urlencode 'groupNumber=pd-413901'

      - name: check DB data
        run: curl -X GET http://127.0.0.1:3000/getUsers
        

